In [2]:
import pandas as pd
import numpy as np
import warnings

##Importación de los datos
data = pd.read_csv('evol1_ann_table1.csv')
data

,NODE_1_length_58499_cov_4.208781,7996,C,T,225.421,25,T.1,missense_variant,MODERATE,KAGFDIAF_00010,...,null.16,Unnamed: 477,Unnamed: 478,n.7996C>T,Unnamed: 480,Unnamed: 481,Unnamed: 482,Unnamed: 483,Unnamed: 484,Unnamed: 485
0,NODE_1_length_58499_cov_4.208781,19176,A,T,225.417,28.0,T,stop_lost&splice_region_variant,HIGH,KAGFDIAF_00021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NODE_1_length_58499_cov_4.208781,28986,T,A,225.417,23.0,A,synonymous_variant,LOW,KAGFDIAF_00031,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NODE_1_length_58499_cov_4.208781,38746,T,A,228.316,30.0,A,upstream_gene_variant,MODIFIER,KAGFDIAF_00035,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NODE_1_length_58499_cov_4.208781,38894,T,A,228.246,26.0,A,upstream_gene_variant,MODIFIER,KAGFDIAF_00035,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NODE_2_length_51549_cov_4.432322,119,A,C,225.417,17.0,C,upstream_gene_variant,MODIFIER,KAGFDIAF_00056,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785,NODE_733_length_111_cov_10.750000,89,T,A,96.8051,26.0,A,intergenic_region,MODIFIER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
786,NODE_733_length_111_cov_10.750000,93,T,C,102.134,24.0,C,intergenic_region,MODIFIER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
787,NODE_772_length_109_cov_4.370370,75,G,A,93.9245,17.0,A,intergenic_region,MODIFIER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
788,NODE_777_length_107_cov_26.480769,43,A,G,114.52,30.0,G,intergenic_region,MODIFIER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
789,NODE_777_length_107_cov_26.480769,80,A,G,164.057,30.0,G,intergenic_region,MODIFIER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data_ = data[data['25'] >= 30]
data_

,NODE_1_length_58499_cov_4.208781,7996,C,T,225.421,25,T.1,missense_variant,MODERATE,KAGFDIAF_00010,...,null.16,Unnamed: 477,Unnamed: 478,n.7996C>T,Unnamed: 480,Unnamed: 481,Unnamed: 482,Unnamed: 483,Unnamed: 484,Unnamed: 485
2,NODE_1_length_58499_cov_4.208781,38746,T,A,228.316,30.0,A,upstream_gene_variant,MODIFIER,KAGFDIAF_00035,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NODE_2_length_51549_cov_4.432322,37395,G,T,225.417,30.0,T,missense_variant,MODERATE,KAGFDIAF_00085,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NODE_3_length_51316_cov_4.268430,41356,G,T,225.417,31.0,T,synonymous_variant,LOW,KAGFDIAF_00135,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NODE_4_length_43486_cov_4.473326,16381,A,T,228.325,32.0,T,missense_variant,MODERATE,KAGFDIAF_00160,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NODE_4_length_43486_cov_4.473326,34995,GGGTG,GGGTGGTG,228.332,33.0,GGGTGGTG,conservative_inframe_insertion,MODERATE,KAGFDIAF_00179,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
782,NODE_733_length_111_cov_10.750000,59,G,A,92.4709,30.0,A,intergenic_region,MODIFIER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
783,NODE_733_length_111_cov_10.750000,62,A,G,92.487,30.0,G,intergenic_region,MODIFIER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
784,NODE_733_length_111_cov_10.750000,74,C,A,92.4507,30.0,A,intergenic_region,MODIFIER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
788,NODE_777_length_107_cov_26.480769,43,A,G,114.52,30.0,G,intergenic_region,MODIFIER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
789,NODE_777_length_107_cov_26.480769,80,A,G,164.057,30.0,G,intergenic_region,MODIFIER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:

data_evol1 = data_[data_['MODERATE']=='HIGH']
data_evol1

,NODE_1_length_58499_cov_4.208781,7996,C,T,225.421,25,T.1,missense_variant,MODERATE,KAGFDIAF_00010,...,null.16,Unnamed: 477,Unnamed: 478,n.7996C>T,Unnamed: 480,Unnamed: 481,Unnamed: 482,Unnamed: 483,Unnamed: 484,Unnamed: 485
53,NODE_12_length_31822_cov_4.522649,3530,T,TG,225.417,38.0,TG,frameshift_variant,HIGH,KAGFDIAF_00408,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NODE_16_length_28105_cov_4.645312,23540,T,A,225.417,48.0,A,stop_gained,HIGH,KAGFDIAF_00530,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,NODE_27_length_24632_cov_4.384058,21716,TG,TGG,228.385,36.0,TGG,frameshift_variant,HIGH,KAGFDIAF_00823,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,NODE_47_length_19935_cov_4.144920,15935,GAAAA,GAAAAA,228.231,42.0,GAAAAA,frameshift_variant,HIGH,KAGFDIAF_01225,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,NODE_106_length_12735_cov_4.212618,5233,T,A,225.417,30.0,A,stop_lost&splice_region_variant,HIGH,KAGFDIAF_02081,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,NODE_108_length_12718_cov_4.092711,12416,A,C,225.417,31.0,C,stop_lost&splice_region_variant,HIGH,KAGFDIAF_02112,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301,NODE_124_length_11842_cov_4.158395,9973,TCGGCGCGGCGCGGCGCGG,TCGGCGCGGCGCGG,228.219,53.0,TCGGCGCGGCGCGG,frameshift_variant,HIGH,KAGFDIAF_02300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
330,NODE_142_length_10787_cov_4.290719,4697,TGGGG,TGGG,228.101,70.0,TGGG,frameshift_variant,HIGH,KAGFDIAF_02490,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
538,NODE_345_length_3705_cov_4.079178,749,T,A,225.417,30.0,A,stop_lost&splice_region_variant,HIGH,KAGFDIAF_03785,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,NODE_422_length_2271_cov_4.346119,1828,T,A,39.3526,33.0,A,stop_lost&splice_region_variant,HIGH,KAGFDIAF_04009,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
data_evol1.columns

Index(['NODE_1_length_58499_cov_4.208781', '7996', 'C', 'T', '225.421', '25',
       'T.1', 'missense_variant', 'MODERATE', 'KAGFDIAF_00010',
       ...
       'null.16', 'Unnamed: 477', 'Unnamed: 478', 'n.7996C>T', 'Unnamed: 480',
       'Unnamed: 481', 'Unnamed: 482', 'Unnamed: 483', 'Unnamed: 484',
       'Unnamed: 485'],
      dtype='object', length=486)

In [6]:
data_evol1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 53 to 608
Columns: 486 entries, NODE_1_length_58499_cov_4.208781 to Unnamed: 485
dtypes: float64(209), int64(1), object(276)
memory usage: 38.0+ KB

In [8]:
data_evol1.to_csv("data_evol1.1.csv", index=False)

In [9]:
##Importación de los datos
data2 = pd.read_csv('evol2_ann_table1.csv')
data2

,NODE_1_length_58499_cov_4.208781,7996,C,T,225.417,44,T.1,missense_variant,MODERATE,KAGFDIAF_00010,...,null.16,Unnamed: 477,Unnamed: 478,n.7996C>T,Unnamed: 480,Unnamed: 481,Unnamed: 482,Unnamed: 483,Unnamed: 484,Unnamed: 485
0,NODE_1_length_58499_cov_4.208781,19176,A,T,225.4170,26,T,stop_lost&splice_region_variant,HIGH,KAGFDIAF_00021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NODE_1_length_58499_cov_4.208781,28986,T,A,228.2720,27,A,synonymous_variant,LOW,KAGFDIAF_00031,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NODE_1_length_58499_cov_4.208781,38746,T,A,225.4170,25,A,upstream_gene_variant,MODIFIER,KAGFDIAF_00035,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NODE_1_length_58499_cov_4.208781,38894,T,A,225.4170,28,A,upstream_gene_variant,MODIFIER,KAGFDIAF_00035,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NODE_2_length_51549_cov_4.432322,8023,A,T,38.9117,45,T,missense_variant,MODERATE,KAGFDIAF_00061,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
731,NODE_713_length_135_cov_14.637500,54,CTT,CT,152.7780,33,CT,intergenic_region,MODIFIER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
732,NODE_720_length_115_cov_13.583333,56,A,G,78.3756,14,G,intergenic_region,MODIFIER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
733,NODE_720_length_115_cov_13.583333,58,C,G,78.3756,14,G,intergenic_region,MODIFIER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
734,NODE_720_length_115_cov_13.583333,95,G,A,77.3972,13,A,intergenic_region,MODIFIER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
735,NODE_772_length_109_cov_4.370370,75,G,A,148.6440,10,A,intergenic_region,MODIFIER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
data2_ = data2[data2['44'] >= 37]
data2_

,NODE_1_length_58499_cov_4.208781,7996,C,T,225.417,44,T.1,missense_variant,MODERATE,KAGFDIAF_00010,...,null.16,Unnamed: 477,Unnamed: 478,n.7996C>T,Unnamed: 480,Unnamed: 481,Unnamed: 482,Unnamed: 483,Unnamed: 484,Unnamed: 485
4,NODE_2_length_51549_cov_4.432322,8023,A,T,38.9117,45,T,missense_variant,MODERATE,KAGFDIAF_00061,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NODE_3_length_51316_cov_4.268430,31317,G,T,225.4170,45,T,synonymous_variant,LOW,KAGFDIAF_00126,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NODE_5_length_40631_cov_4.277208,22103,T,A,225.4170,61,A,missense_variant,MODERATE,KAGFDIAF_00204,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NODE_6_length_40131_cov_4.614208,37977,A,T,225.4170,40,T,missense_variant,MODERATE,KAGFDIAF_00251,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NODE_8_length_34660_cov_4.311718,15676,T,A,204.2460,39,A,upstream_gene_variant,MODIFIER,KAGFDIAF_00300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,NODE_703_length_156_cov_3.207921,68,C,T,214.8290,65,T,intergenic_region,MODIFIER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
726,NODE_703_length_156_cov_3.207921,89,T,A,222.3990,59,A,intergenic_region,MODIFIER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
727,NODE_703_length_156_cov_3.207921,90,T,C,221.5010,59,C,intergenic_region,MODIFIER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
728,NODE_703_length_156_cov_3.207921,110,G,A,64.0348,48,A,intergenic_region,MODIFIER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
729,NODE_703_length_156_cov_3.207921,134,T,C,86.2953,37,C,intergenic_region,MODIFIER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_filtrado2 = data2_[data2_['MODERATE']=='HIGH']

In [12]:
df_filtrado2

,NODE_1_length_58499_cov_4.208781,7996,C,T,225.417,44,T.1,missense_variant,MODERATE,KAGFDIAF_00010,...,null.16,Unnamed: 477,Unnamed: 478,n.7996C>T,Unnamed: 480,Unnamed: 481,Unnamed: 482,Unnamed: 483,Unnamed: 484,Unnamed: 485
44,NODE_12_length_31822_cov_4.522649,3530,T,TG,225.4170,46,TG,frameshift_variant,HIGH,KAGFDIAF_00408,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,NODE_16_length_28105_cov_4.645312,23540,T,A,225.4170,53,A,stop_gained,HIGH,KAGFDIAF_00530,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137,NODE_47_length_19935_cov_4.144920,15935,GAAAA,GAAAAA,228.1810,39,GAAAAA,frameshift_variant,HIGH,KAGFDIAF_01225,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,NODE_66_length_16713_cov_4.246668,14839,CA,CAA,222.4040,67,CAA,frameshift_variant,HIGH,KAGFDIAF_01551,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,NODE_66_length_16713_cov_4.246668,14890,TAA,TA,40.2219,37,TA,frameshift_variant,HIGH,KAGFDIAF_01551,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,NODE_108_length_12718_cov_4.092711,12416,A,C,225.4170,47,C,stop_lost&splice_region_variant,HIGH,KAGFDIAF_02112,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
#upstream, downstream, intragenic
data_evol2 = df_filtrado2[df_filtrado2['upstream_gene_variant'] != 'downstream_gene_variant']
data_evol2

,NODE_1_length_58499_cov_4.208781,7996,C,T,225.417,44,T.1,missense_variant,MODERATE,KAGFDIAF_00010,...,null.16,Unnamed: 477,Unnamed: 478,n.7996C>T,Unnamed: 480,Unnamed: 481,Unnamed: 482,Unnamed: 483,Unnamed: 484,Unnamed: 485
44,NODE_12_length_31822_cov_4.522649,3530,T,TG,225.4170,46,TG,frameshift_variant,HIGH,KAGFDIAF_00408,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,NODE_16_length_28105_cov_4.645312,23540,T,A,225.4170,53,A,stop_gained,HIGH,KAGFDIAF_00530,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137,NODE_47_length_19935_cov_4.144920,15935,GAAAA,GAAAAA,228.1810,39,GAAAAA,frameshift_variant,HIGH,KAGFDIAF_01225,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,NODE_66_length_16713_cov_4.246668,14839,CA,CAA,222.4040,67,CAA,frameshift_variant,HIGH,KAGFDIAF_01551,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,NODE_66_length_16713_cov_4.246668,14890,TAA,TA,40.2219,37,TA,frameshift_variant,HIGH,KAGFDIAF_01551,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,NODE_108_length_12718_cov_4.092711,12416,A,C,225.4170,47,C,stop_lost&splice_region_variant,HIGH,KAGFDIAF_02112,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
data_evol2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 44 to 264
Columns: 486 entries, NODE_1_length_58499_cov_4.208781 to Unnamed: 485
dtypes: float64(310), int64(2), object(174)
memory usage: 22.8+ KB

In [15]:
data_evol2.to_csv("data_evol2.csv", index=False)